swagger: "2.0"
info:
  version: 1.0.2
  title: Stock API
  description: A simple API to manage stock
schemes:
  - https
  - http
host: fit-stock-api.herokuapp.com
basePath: /api/v1
tags:
- name: "user"
  description: "Operations about user"
- name: "profiles"
  description: "Operations about profile"
- name: "modules"
  description: "Operations about modules"
paths:
  /user:
    get:
      tags:
        - "user"
      summary: Get all users
      description: Returns a list containing all users.
      consumes:
      - "application/json"
      responses:
        200:
          description: A list of User
          schema:
            $ref: "#/definitions/User"
    post:
      tags:
      - "user"
      summary: "Create a new user"
      description: "Create a new unique user."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User information"
        required: true
        schema:
          $ref: "#/definitions/UserWithoutId"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreatedUser"
  /user/{id}:
    put:
      tags:
      - "user"
      summary: "Update an user"
      description: "Update an user."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id" 
        in: "path"
        description: "user id"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/CreatedUser"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreatedUser"
    delete:
      tags:
      - "user"
      summary: "Delete an user"
      description: "Delete an user."
      parameters:
      - name: "id"
        in: "path"
        description: "user id"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
  /profiles:
    get:
      tags:
        - "profiles"
      summary: Get all profiles
      description: Returns a list containing all profiles.
      consumes:
      - "application/json"
      responses:
        200:
          description: A list of Profiles
          schema:
            $ref: "#/definitions/Profile"
  /modules:
    get:
      tags:
        - "modules"
      summary: Get all modules
      description: Returns a list containing all modules.
      consumes:
      - "application/json"
      responses:
        200:
          description: A list of Modules
          schema:
            $ref: "#/definitions/Module"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int16"
      name:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      profileId:
        type: "integer"
        format: "int16"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
      deletedAt:
        type: "string"
        format: "date-time"
    xml:
      name: "User"
  CreatedUser:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int16"
      name:
        type: "string"
        example: "Admin"
      username:
        type: "string"
        example: "admin"
      password:
        type: "string"
        example: "123456"
      profileId:
        type: "integer"
        example: 1
        format: "int16"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
      deletedAt:
        type: "string"
        format: "date-time"
  UserWithoutId:
    type: "object"
    properties:
      name:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      profileId:
        type: "integer"
        format: "int16"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
      deletedAt:
        type: "string"
        format: "date-time"
    xml:
      name: "UserWithoutId"
  Profile:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int16"
        example: 1
      name:
        type: "string"
        example: "Admin"
      description:
        type: "string"
        example: "Usuário com todas as permissões possíveis."
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
      deletedAt:
        type: "string"
        format: "date-time"
    xml:
      name: "Profile"
  Module:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int16"
        example: 1
      name:
        type: "string"
        example: "home"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
      deletedAt:
        type: "string"
        format: "date-time"
    xml:
      name: "Profile"